### PR TITLE
fix(unetsocket.c): manually initialising malloced structures.

### PR DESCRIPTION
**Pull request by notthetup**
Pending : Test on Windows

### CODE REVIEW

**Comment by prasadtiru** [comment]
The file on which you have made changes doesn't seem to be one from the master. Did you branch off from master, made changes and created this PR ? Could you re-check ? In the latest `unet.c`, the change you have made should be on line 151 (https://github.com/org-arl/unet-contrib/blob/master/unetsocket/c/unet.c#L151)

**Comment by notthetup** [comment]
Thanks @prasadtiru fixed it.

**Comment by prasadtiru** [comment]
Tested this change on Windows. Works fine.

**Review by mchitre — COMMENTED** [review]
I believe the zero-ed assumption only is needed for `usock` and not `agents`? Would it be better to initialize the struct explicitly after `malloc`?

I personally feel slightly uncomfortable using `calloc` to meet that assumption, as against actually initializing all fields in `usock` explicitly after `malloc`. While the `calloc` version is perhaps more efficient, it makes strong assumptions about memory representation of data types in the struct. The explicit initialization drops such assumptions, and makes the initial values clearer to the reader.

The opinion is not a very strong one, so I'll leave it to you to decide to adopt or not.

**Comment by notthetup** [comment]
Agreed. I will refactor back to `malloc` and manually initializing all fields. I prefer that too.

**Comment by notthetup** [comment]
Updated with only "zeroing" the relevant properties.

**Review by manuignatius — APPROVED** [review]

**Review by mchitre — APPROVED** [review]

**Pull request merged**
